// lit/ar-button.js
import {LitElement, html, css} from 'lit';

export class ArButton extends LitElement {
  static get properties() {
    return {
      model: {type: String},
      qrTitle: {type: String},
      qrText: {type: String},
      buttonText: {type: String},

      showQrCode: {type: Boolean, state: true},
      showButton: {type: Boolean, state: true}
    };
  }

  baseUrl = 'https://dev.yago.cloud';
  modelLink = '';
  config = {
    site_url: null,
    quicklook_link: null,
    qr_config: null,
    ar_button_config: null,
};

  constructor() {
    super();

    // Props with default values
    this.model = '';
    this.buttonText = 'Default Btn Text';
    this.qrTitle = 'Default QR Title';
    this.qrText = 'Default QR Text';

    this.showQrCode = false;
    this.showButton = false;
  }

  async connectedCallback() {
    super.connectedCallback()

    // Fetch config from yago server and update when ready
    this.config = await this.getConfig();
    console.log(this.config)

    this.showButton = true;
  }

  render() {
    this.modelLink = new URL(`/v/${this.model}`, this.baseUrl);

    const modal = html`
      <div class="ar-button-modal ${this.showQrCode ? '' : 'hidden'}">
        <div class="modal-inner" role="dialog">  
        <div class="ar-modal-header">
          <h2 class="ar-modal-content">${this.qrTitle}</h2>
          <button type="button" class="button-close" @click="${this.closeModalWindow}">✕</button>
        </div>
        <section class="ar-modal-body">
          <div class="qr-element"></div>
          <p class="ar-modal-content" :style="{ width: qrSize + 'px' }">
            ${this.qrText}
          </p>
        </section>
        <div class="ar-modal-footer">
          <p>
            Powered by
            <a href="https://yago.cloud/">
              Yago
              <img src="https://yago.cloud/static/yago/img/yago_icon.png" />
            </a>
          </p>
        </div>
        </div>
      </div>
    `;

    return html`
      <div
        id="${this.elementId}"
        class="ar-button ${!this.showButton ? 'hidden' : ''}">

        <a
          rel="ar"
          href="${this.modelLink}"
          @click=${this.startAr}
          class="ar-link external">
          <!-- image tag as first child is required for iOS -->
          <img />
          <!-- ToDo: AR Icon Component -->
          ${this.buttonText}
        </a>
        ${ html`${modal}` }
      </div>
    `;
  }

  _onClick() {
    this.count++;
    this.dispatchEvent(new CustomEvent('count-changed'));
  }

  startAr(e) {
    e.preventDefault();
    this.showQrCode = true;

  }

  closeModalWindow() {
    this.showQrCode = false;
  }

  async getConfig() {
    try {
        const configResponse = await fetch(`${this.baseUrl}/api/models/${this.model}/embed/options/`);
        if (!configResponse.ok) throw configResponse;
        return await configResponse.json();
    } catch (e) {
        // Fallback to fixed scaling
        return this.config;
    }
}
  
  get elementId() {
    return 'ar-button-' + this.model; 
  }

  static get styles() {
    const buttonStyles = css`
      .ar-button {
        display: inline-block;
        font-family: var(--font-family, Avenir, Helvetica, Arial, sans-serif);
      }
      
      .ar-button > .ar-link {
        background-color: var(--background-color, #074e68);
        color: var(--color, #ffffff);
        text-decoration: var(--text-decoration, none);
        border: var(--border, none);
        border-radius: var(--border-radius, 8px);
        padding: var(--padding, 8px 16px);
        display: inline-flex;
        align-items: center;

        transition: background-color 0.2s ease;
      }

      .hidden {
        display: none !important;
      }
    `;

    const modalStyles = css`
      .ar-button-modal {
          position: fixed;
          top: 0;
          bottom: 0;
          left: 0;
          right: 0;
          z-index: 9999;
          display: flex;
          justify-content: center;
          align-items: center;
          background-color: rgba(0, 0, 0, 0.3);
          padding: 10px;

          transition: .3s opacity ease;
          opacity: 1;
      }
      
      .ar-button-modal .modal-inner {
          display: flex;
          flex-direction: column;
          border-radius: 1em;
          background: #ffffff;
          box-shadow: 1px 1px 20px 1px #838383;
          overflow-x: auto;
          /*flex: 1;
          max-width: 520px;*/
      }
      
      .ar-button-modal .ar-modal-header {
          display: flex;
          justify-content: flex-end;
          padding: 15px;
      }
      
      .ar-button-modal .button-close {
          border: none;
          font-size: 38px;
          cursor: pointer;
          color: #a99fa4;
          background: transparent;
          font-weight: normal;
          margin: 0;
          padding: 0;
      }
      
      .ar-button-modal .button-close:focus {
          outline: none;
      }
      
      .ar-button-modal .ar-modal-body {
          position: relative;
          margin: 20px 60px;
      }
      
      .ar-button-modal .ar-modal-footer {
          color: #000000;
          border-top: 1px solid #888888;
          display: inline-flex;
          flex-direction: column;
          align-items: center;
      }
      
      @media (-webkit-min-device-pixel-ratio: 2) {
          .ar-button-modal .ar-modal-footer {
              border-top: 0.5px solid #888888;
          }
      }
      
      .ar-button-modal .ar-modal-footer a {
          color: inherit;
          text-decoration: none;
      }
      
      .ar-button-modal .ar-modal-footer img {
          position: relative;
          top: 2px;
          margin: 0 4px;
          height: 16px;
      }
      
      .ar-button-modal .ar-modal-footer p {
          font-family: var(--font-family, Avenir, Helvetica, Arial, sans-serif);
          font-size: 16px;
          margin: 0;
          padding: 16px 0;
      }
      .ar-button {
          display: inline-block;
          font-family: var(--font-family, Avenir, Helvetica, Arial, sans-serif);
      }
      
      .ar-button > .ar-link {
          background-color: var(--background-color, #074e68);
          color: var(--color, #ffffff);
          text-decoration: var(--text-decoration, none);
          border: var(--border, none);
          border-radius: var(--border-radius, 8px);
          padding: var(--padding, 8px 16px);
          display: inline-flex;
          align-items: center;
      }
      
      .ar-button .ar-icon {
          width: var(--ar-icon-height, 30px);
          height: var(--ar-icon-height, 30px);
          margin-right: 4px;
      }
      
      .ar-button .ar-icon-path {
          fill: var(--color, #ffffff);
      }
      
      .qr-canvas {
          display: block;
      }
      
      .qr-element {
          display: flex;
          justify-content: center;
          align-content: center;
          padding: 12px;
          background: var(--qr-code-border-color, #074e68);
      }
      
      .qr-element img {
          display: block;
      }
      
      .ar-modal-header h2 {
          margin: 0;
          padding: 15px 10px 10px 10px;
      }
      
      .ar-modal-content {
          color: #000000;
          text-align: left;
      }
      
      h2.ar-modal-content {
          font-family: var(--font-family, Avenir, Helvetica, Arial, sans-serif);
          font-size: 24px;
          margin: 0;
          padding: 20px 0;
      }
      
      p.ar-modal-content {
          font-family: var(--font-family, Avenir, Helvetica, Arial, sans-serif);
          font-size: 16px;
          margin: 0;
          padding: 0 0 16px 0;
      }
    `;

    return css`${buttonStyles} ${modalStyles}`;
  }
}

window.customElements.define('ar-button', ArButton);

// src/components/ar-button.vue
<template>
    <div :id="elementId" class="ar-button">
        <a ref="ar" rel="ar" :href="modelLink" @click="startAR" class="ar-link external">
            <!-- image tag as first child is required for iOS -->
            <img />
            <ar-icon />
            {{ text }}
        </a>
        <modal-window v-show="showQrCode" @close="showQrCode = false">
            <div class="qr-element" ref="qrcode"></div>
            <h2 class="ar-modal-content">{{ qrTitle }}</h2>
            <p class="ar-modal-content" :style="{ width: qrSize + 'px' }">
                {{ qrText }}
            </p>
        </modal-window>
        <browser-unsupported :modelLink="modelLink" v-show="showBrowserHint" @close="showBrowserHint = false" />
    </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';
import ARIcon from './ar-icon.vue';
import modal from './modal-window.vue';
import BrowserUnsupported from './browser-unsupported.vue';
import QRCodeStyling, { DrawType } from 'qr-code-styling';

declare global {
    interface Window {
        MSStream: any;
    }
}

interface Config {
    site_url: string | null | undefined;
    quicklook_link: string | null | undefined;
    qr_config: object | null | undefined;
}

@Component({
    name: 'ar-button',
    components: {
        'ar-icon': ARIcon,
        'modal-window': modal,
        'browser-unsupported': BrowserUnsupported,
    },
})
export default class ARButton extends Vue {
    @Prop()
    private model!: string;

    @Prop({ default: 'Place in your space' })
    private text!: string;

    @Prop({ default: 'Here we go!' })
    private qrTitle!: string;

    @Prop({ default: 'Scan the QR Code to place the model in your space.' })
    private qrText!: string;

    @Prop({ default: 200 })
    private qrSize!: number;

    public baseUrl = process.env.VUE_APP_GENIE_BASE_URL;
    public modelLink: URL;

    public isArSupported = false;
    public isBrowserSupported = true;

    public showQrCode = false;
    public showBrowserHint = false;

    public qrCode: QRCodeStyling | null = null;
    public qrOptions = {
        width: this.qrSize - 24,
        height: this.qrSize - 24,
        type: 'svg' as DrawType,
        data: '',
        margin: 10,
        errorCorrectionLevel: 'Q',
        image: undefined,
    };

    public config: Config = {
        site_url: null,
        quicklook_link: null,
        qr_config: null,
    };

    public get elementId() {
        return 'ar-button-' + this.model;
    }

    public constructor() {
        super();
        this.modelLink = new URL(`/v/${this.model}`, this.baseUrl);
    }

    public async mounted() {
        // Fetch config from genie server and update when ready
        this.config = await this.getConfig();

        // On iOS: Change model link to open USDZ with AR Quicklook directly (Genie Redirect to USDZ model)
        if (this.isIos() && this.isQuicklookSupported() && this.config.quicklook_link) {
            this.isArSupported = true;
            this.isBrowserSupported = this.checkIosBrowserSupport();
            if (this.isBrowserSupported) {
                this.modelLink = new URL(this.config.quicklook_link);
            }
            const link = this.$refs.ar as HTMLAnchorElement;
            link.addEventListener('message', this.onCallToActionButtonTapped);
        }

        // On Android: Change link to open SceneViewer directly. Assume AR is supported, if not, a fallback page will be shown
        if (this.isAndroid()) {
            this.isArSupported = true;
            this.modelLink = this.buildSceneviewerLink();
        }

        // Initialize QR code drawing style
        if ('qr_config' in this.config) {
            Object.assign(this.qrOptions, this.config.qr_config);

            // Use higher error correction level when QR Code has image
            if ('image' in this.qrOptions && this.qrOptions['image']) {
                this.qrOptions['errorCorrectionLevel'] = 'H';
            }
        }
        this.qrCode = new QRCodeStyling(this.qrOptions);
        this.qrCode.append(this.$refs.qrcode as HTMLElement);
    }

    public onCallToActionButtonTapped(event: Event): void {
        if ((event as any).data == '_apple_ar_quicklook_button_tapped') {
            if (this.config.site_url) {
                window.location.assign('');
            } else {
                console.error('Model site_url must be defined when using callToAction.');
            }
        }
    }

    private buildSceneviewerLink(): URL {
        // Pass current location as backlink. Will be shown as 'Visit' Link in SceneViewer
        const pageUrl = new URL(window.location.toString());
        if (!pageUrl.hash || pageUrl.hash.startsWith('#ar-button')) {
            pageUrl.hash = '#' + this.elementId;
        }
        const encodedUrl = encodeURIComponent(pageUrl.toString());

        return new URL(`/v/${this.model}/sceneviewer?page_url=${encodedUrl}`, this.baseUrl);
    }

    private isIos(): boolean {
        return (
            (/iPad|iPod|iPhone/.test(navigator.platform) ||
                (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1)) &&
            !window.MSStream
        );
    }

    private isAndroid(): boolean {
        return /android/i.test(navigator.userAgent);
    }

    private isQuicklookSupported(): boolean {
        const link = this.$refs.ar as HTMLAnchorElement;
        if (link) return link.relList.supports('ar');
        return false;
    }

    private isWKWebView(): boolean {
        const _window = window as any;
        return _window.webkit && _window.webkit.messageHandlers;
    }

    private checkIosBrowserSupport(): boolean {
        // On iOS, some WKWebView based browsers like Chrome and Firefox do support Quicklook links,
        // while others like Brave, Opera or DuckDuckGo do not. They either offer to download the
        // USDZ File or, worse, show it's plain content. It's hard to detect unsupported browsers
        // since it can also be an embedded WebView in an App (e.g. LinkedIn In-App Browser).
        // Therefore, if WKWebView is detected, we only allow browsers with known Quicklook support.

        if (this.isWKWebView()) {
            // https://chromium.googlesource.com/chromium/src/+/HEAD/docs/ios/user_agent.md
            const isChrome = navigator.userAgent.includes('CriOS/');

            // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox#firefox_for_ios
            const isFirefox = navigator.userAgent.includes('FxiOS/');

            // https://blogs.windows.com/msedgedev/2017/10/05/microsoft-edge-ios-android-developer/
            const isEdge = navigator.userAgent.includes('EdgiOS/');

            // Only allow whitelisted browsers
            return isChrome || isFirefox || isEdge;
        }

        // All other browsers like Safari, SFSafariViewController and others are feature detected
        return true;
    }

    public startAR(e: Event) {
        // Show error on unsupported browsers (iOS WKWebView based third party browsers)
        if (!this.isBrowserSupported) {
            e.preventDefault();
            this.showBrowserHint = true;
            return;
        }

        // Show QR Code on devices without AR Support
        if (!this.isArSupported) {
            e.preventDefault();

            // Pass current document url in QR code as page_url parameter
            // This ensures correct return urls in single page apps
            const encodedUrl = encodeURIComponent(window.location.toString());
            const qrUrl = new URL('?page_url=' + encodedUrl, this.modelLink);

            this.renderQrCode(qrUrl);
            this.showQrCode = true;
        }

        // On AR supported devices just follow the link
    }

    private async renderQrCode(url: URL) {
        this.qrOptions['data'] = url.toString();
        this.qrCode?.update(this.qrOptions);
    }

    private async getConfig(): Promise<Config> {
        try {
            const configResponse = await fetch(`${this.baseUrl}/api/models/${this.model}/embed/options/`);
            if (!configResponse.ok) throw configResponse;
            return await configResponse.json();
        } catch (e) {
            // Fallback to fixed scaling
            return this.config;
        }
    }
}
</script>

<style>
.ar-button {
    display: inline-block;
    font-family: var(--font-family, Avenir, Helvetica, Arial, sans-serif);
}

.ar-button > .ar-link {
    background-color: var(--background-color, #074e68);
    color: var(--color, #ffffff);
    text-decoration: var(--text-decoration, none);
    border: var(--border, none);
    border-radius: var(--border-radius, 8px);
    padding: var(--padding, 8px 16px);
    display: inline-flex;
    align-items: center;
}

.ar-button .ar-icon {
    width: var(--ar-icon-height, 30px);
    height: var(--ar-icon-height, 30px);
    margin-right: 4px;
}

.ar-button .ar-icon-path {
    fill: var(--color, #ffffff);
}

.qr-canvas {
    display: block;
}

.qr-element {
    display: flex;
    justify-content: center;
    align-content: center;
    padding: 12px;
    background: var(
        --qr-code-border-color,
        linear-gradient(90deg, rgba(245, 135, 85, 1) 0%, rgba(255, 193, 160, 1) 43%, rgba(195, 218, 224, 1) 68%)
    );
}

.qr-element img {
    display: block;
}

.ar-modal-header h2 {
    margin: 0;
    padding: 15px 10px 10px 10px;
}

.ar-modal-content {
    color: #000000;
    text-align: left;
}

h2.ar-modal-content {
    font-family: var(--font-family, Avenir, Helvetica, Arial, sans-serif);
    font-size: 24px;
    margin: 0;
    padding: 20px 0;
}

p.ar-modal-content {
    font-family: var(--font-family, Avenir, Helvetica, Arial, sans-serif);
    font-size: 16px;
    margin: 0;
    padding: 0 0 16px 0;
}
</style>
